export const MAX_POOL_SIZE = 20;
export const IDLE_TIMEOUT_MILLIS = 30000;
export const CONNECTION_TMEOUT_MILLIS = 2000;
export const SATELITE_PROPAGATION_LIMIT = 100;
export const SATELITE_PROPAGATION_DEBRIS_LIMIT = 30;

export const CONJUNCTION_ALERT_MAX_SEPARATION_KM = 500;
